## kubectl get po --show-labels


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: java
    env: dev
    client: TCS
spec:
  containers:
    - name: nginx-c 
      image: kkeducationb2/java-webapp:1.1
      ports:
        - containerPort: 8080