apiVersion: v1
kind: Pod
metadata:
  name: javawebapp
  labels:
    app: javawebapp
spec:
  containers:
    - name: javawebapp
      image: kkeducationb2/java-webapp:1.1
      ports: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvcnp
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080