apiVersion: v1
kind: Pod 
metadata:
  name: pod-2
  labels:
    app: paytm
    env: dev
spec:
  containers:
    - name: cont-1
      image: shaikmustafa/dm
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: loadsvc
spec:
  type: LoadBalancer
  selector: 
    app: paytm
  ports:
    - port: 80
      targetPort: 80