## kubectl get rs
## kubectl describe rs <rs_name>
## kubectl scale rs <rs_name> --replicas=5
## kubectl delete rs <rs_name>


---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/paytm:bus
          ports:
            - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata: 
  name: appsvcnp
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31001