## kubectl get secret
## echo "rammohan" | base64  ----> encode command
## echo "Password@12345" | base64 
## kubectl describe secret <secret_name>
## kubectl get secret sec1 -o yaml
## echo "cmFtbW9oYW4K" | base64 -d  --> decode command
## kubectl create secret generic mysec --from-literal=username=ravi --from-literal=password=admin@123 ----> imparative way
## we can create secret same as configmap


---
apiVersion: v1 
kind: Secret 
metadata:
  name: sec1
data:
  NAME: cmFtbW9oYW4K 
  PASSWORD: cGFzc3dvcmRAMTIzNDUK


---
apiVersion: v1 
kind: Pod 
metadata:
  name: ex-pod-secret
spec:
  containers:
    - name: cont-1
      image: shaikmustafa/dm 
      ports: 
        - containerPort: 80
      envFrom:
        - secretRef: 
            name: sec1
        - secretRef:
            name: mysec
        

---
apiVersion: v1 
kind: Pod 
metadata:
  name: ex-pod-secret-1
spec:
  containers:
    - name: cont-1
      image: shaikmustafa/dm 
      ports: 
        - containerPort: 80
      env:
        - name: mysqlpassword
          valueFrom:
            secretKeyRef:
              name: sec1
              key: PASSWORD
        - name: username1
          valueFrom:
            secretKeyRef:
              name: mysec 
              key: username
            