## kubectl config view ---> to know cluster details and user details in cluster
## create a user
## https://medium.com/@muppedaanvesh/a-hand-on-guide-to-kubernetes-rbac-with-a-user-creation-%EF%B8%8F-1ad9aa3cafb1

## kubectl config set-context flm --cluster=kubernetes --user=dev-user  ---> create a context for the user
## kubectl config use-context flm --> switch to the context


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: dev
rules:
  - apiGroups: ["*"]
    resources: ["pods","deployments"]
    verbs: ["get","list","create"]

  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get","list","create","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: dev
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io