---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["pods","deployments","replicasets"]
    verbs: ["get","list","create"]

  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get","list","create","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-Cluster-role-binding
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-cluster-role
  apiGroup: rbac.authorization.k8s.io