---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          container:
            - name: cont-1
              image: ubuntu
              command: ["/bin/bash", "-c", "sudo apt update -y; sleep 30"]