# statefulset, pvc , headless service 

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 2
  serviceName: "rabbitmq-headless"
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        imagePullPolicy: Always
        volumeMounts:
          - name: rabbitmq-pvc
            mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: db
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port