apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:  # these are deployment labels
    project: roboshop
    component: mongodb
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels:  # these labels are used to select pods
      project: roboshop
      component: mongodb
      tier: db
    template:
      metadata:
        labels:
          project: roboshop
          component: mongodb
          tier: db
      spec:
        containers:
          - name: mongodb-cont 
            image: joindevops/mongodb:v1 
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: catalogue
                


---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - port: 8080  # service port
      targetPort: 8080  # container port
      protocal: TCP