apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:  # these are deployment labels
    project: roboshop
    component: mongodb
    tier: db 
spec:
  replicas: 1
  selector:
    matchLabels:  # these labels are used to select pods
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb-cont 
          image: joindevops/mongodb:v1 
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
            
                


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
    - port: 27017  # service port
      targetPort: 27017  # container port
      