apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: 2
  serviceName: redis-headless
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-pvc
            mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port