apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:  # these are deployment labels
    project: roboshop
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:  # these labels are used to select pods
      project: roboshop
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend
    spec:
      containers:
        - name: catalogue-cont 
          image: joindevops/catalogue:v1 
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: catalogue

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - port: 8080 # service port
      targetPort: 8080  # container port
      